### ISSUE TITLE
All keys in combo must be pressed twice to fire a second event.

### ISSUE THREAD

**Issue by nphollon** [scottcorgan/keyboard-combo#2]
Below I have a SCCE that illustrates the problem. The program increments a counter when the user types a plus (i.e. shift & equals keys). However, the program will not increment if the user holds down the shift key and presses the equals key repeatedly. Both keys need to be pressed again for a new event to fire. This does not seem like the intended behavior to me.

Let me know if you need any other info. And thanks for sharing your library!

```
module Main exposing (..)

import Keyboard.Combo
import Html


main =
    Html.program
        { init = init
        , subscriptions =
            \model -> Keyboard.Combo.subscriptions model.combos
        , view =
            \model -> Html.text (toString model.counter)
        , update = update
        }


init =
    { counter = 0
    , combos = Keyboard.Combo.init ComboMsg keyboardCombos
    }
        ! []


update msg model =
    case msg of
        ComboMsg comboMsg ->
            { model
                | combos =
                    Keyboard.Combo.update comboMsg model.combos
            }
                ! []

        Increment ->
            { model | counter = model.counter + 1 } ! []


type Action
    = ComboMsg Keyboard.Combo.Msg
    | Increment


keyboardCombos =
    [ Keyboard.Combo.combo2
        ( Keyboard.Combo.shift, Keyboard.Combo.equals )
        Increment
    ]

```

**Comment by scottcorgan** [comment]
That's a great find! Sorry for the delay.

I don't have time yet this week. Did you want to submit a PR?

**Comment by nphollon** [comment]
No problem. It's not urgent for me. I don't have a PR ready, but I will put one together when I have the time.
